# Generated by Django 3.0.6 on 2020-06-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamgt', '0002_auto_20200602_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='MyOptions',
        ),
    ]
