# Generated by Django 3.0.6 on 2020-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamgt', '0005_datamgtoptions_opt1'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt10',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt2',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt3',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt4',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt5',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt6',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt7',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt8',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt9',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
