# Generated by Django 3.0.6 on 2020-06-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamgt', '0006_auto_20200603_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamgtoptions',
            name='name',
        ),
    ]
