# Generated by Django 3.0.6 on 2020-06-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamgt', '0007_remove_datamgtoptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamgtoptions',
            name='opt11',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
